### ISSUE TITLE
some plans are not getting loaded into the GUI on start up of application

### ISSUE THREAD

**Issue by BrandonBoyWonder** [ProofDrivenQuerying/pdq#18]
when a plan is generated from some schemas and tries to be re-loading into the gui it throws the following exception. 

```
2021-01-25 11:53:49,592 ERROR [JavaFX Application Thread] (RelationalTermAdapter.java:35) - null
java.lang.IllegalArgumentException: null
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:128) ~[guava-29.0-jre.jar:?]
	at uk.ac.ox.cs.pdq.algebra.SelectionTerm.<init>(SelectionTerm.java:45) ~[classes/:?]
	at uk.ac.ox.cs.pdq.algebra.SelectionTerm.create(SelectionTerm.java:84) ~[classes/:?]
	at uk.ac.ox.cs.pdq.io.jaxb.adapted.AdaptedRelationalTerm.toRelationalTerm(AdaptedRelationalTerm.java:274) ~[classes/:?]
	at uk.ac.ox.cs.pdq.io.jaxb.adapters.RelationalTermAdapter.unmarshal(RelationalTermAdapter.java:33) ~[classes/:?]
	at uk.ac.ox.cs.pdq.io.jaxb.adapters.RelationalTermAdapter.unmarshal(RelationalTermAdapter.java:20) ~[classes/:?]
	at com.sun.xml.bind.v2.runtime.reflect.AdaptedLister.addToPack(AdaptedLister.java:82) ~[jaxb-runtime-2.4.0-b180725.0644.jar:2.4.0-b180725.0644]
	at com.sun.xml.bind.v2.runtime.unmarshaller.Scope.add(Scope.java:121) ~[jaxb-runtime-2.4.0-b180725.0644.jar:2.4.0-b180725.0644]
	at com.sun.xml.bind.v2.runtime.property.ArrayERProperty$ReceiverImpl.receive(ArrayERProperty.java:213) ~[jaxb-runtime-2.4.0-b180725.0644.jar:2.4.0-b180725.0644]
	at com.sun.xml.bind.v2.runtime.unmarshaller.UnmarshallingContext.endElement(UnmarshallingContext.java:615) ~[jaxb-runtime-2.4.0-b180725.0644.jar:2.4.0-b180725.0644]
	at com.sun.xml.bind.v2.runtime.unmarshaller.SAXConnector.endElement(SAXConnector.java:180) ~[jaxb-runtime-2.4.0-b180725.0644.jar:2.4.0-b180725.0644]
	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.endElement(AbstractSAXParser.java:618) ~[?:?]
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanEndElement(XMLDocumentFragmentScannerImpl.java:1727) ~[?:?]
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:2898) ~[?:?]
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:605) ~[?:?]
	at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.next(XMLNSDocumentScannerImpl.java:112) ~[?:?]
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:541) ~[?:?]
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:888) ~[?:?]
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:824) ~[?:?]
	at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141) ~[?:?]
	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1224) ~[?:?]
	at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:635) ~[?:?]
	at com.sun.xml.bind.v2.runtime.unmarshaller.UnmarshallerImpl.unmarshal0(UnmarshallerImpl.java:258) ~[jaxb-runtime-2.4.0-b180725.0644.jar:2.4.0-b180725.0644]
	at com.sun.xml.bind.v2.runtime.unmarshaller.UnmarshallerImpl.unmarshal(UnmarshallerImpl.java:229) ~[jaxb-runtime-2.4.0-b180725.0644.jar:2.4.0-b180725.0644]
	at javax.xml.bind.helpers.AbstractUnmarshallerImpl.unmarshal(AbstractUnmarshallerImpl.java:170) ~[jaxb-api-2.4.0-b180725.0427.jar:2.3.0]
	at javax.xml.bind.helpers.AbstractUnmarshallerImpl.unmarshal(AbstractUnmarshallerImpl.java:209) ~[jaxb-api-2.4.0-b180725.0427.jar:2.3.0]
	at javax.xml.bind.helpers.AbstractUnmarshallerImpl.unmarshal(AbstractUnmarshallerImpl.java:194) ~[jaxb-api-2.4.0-b180725.0427.jar:2.3.0]
	at uk.ac.ox.cs.pdq.cost.io.jaxb.CostIOManager.readRelationalTermFromRelationaltermWithCost(CostIOManager.java:50) ~[classes/:?]
	at uk.ac.ox.cs.pdq.ui.PDQController.loadPlans(PDQController.java:1628) ~[classes/:?]
	at uk.ac.ox.cs.pdq.ui.PDQController.configurePlans(PDQController.java:1130) ~[classes/:?]
	at uk.ac.ox.cs.pdq.ui.PDQController.initialize(PDQController.java:1099) ~[classes/:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:564) ~[?:?]
	at com.sun.javafx.reflect.Trampoline.invoke(MethodUtil.java:76) ~[javafx.base.jar:?]
	at jdk.internal.reflect.GeneratedMethodAccessor2.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:564) ~[?:?]
	at com.sun.javafx.reflect.MethodUtil.invoke(MethodUtil.java:273) ~[javafx.base.jar:?]
	at com.sun.javafx.fxml.MethodHelper.invoke(MethodHelper.java:83) ~[javafx.fxml.jar:?]
	at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:2673) ~[javafx.fxml.jar:?]
	at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:2548) ~[javafx.fxml.jar:?]
	at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:3323) ~[javafx.fxml.jar:?]
	at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:3280) ~[javafx.fxml.jar:?]
	at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:3249) ~[javafx.fxml.jar:?]
	at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:3222) ~[javafx.fxml.jar:?]
	at javafx.fxml.FXMLLoader.load(FXMLLoader.java:3214) ~[javafx.fxml.jar:?]
	at uk.ac.ox.cs.pdq.ui.PDQApplication.start(PDQApplication.java:106) ~[classes/:?]
	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$9(LauncherImpl.java:846) ~[javafx.graphics.jar:?]
	at com.sun.javafx.application.PlatformImpl.lambda$runAndWait$12(PlatformImpl.java:455) ~[javafx.graphics.jar:?]
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:428) ~[javafx.graphics.jar:?]
	at java.security.AccessController.doPrivileged(AccessController.java:391) ~[?:?]
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:427) ~[javafx.graphics.jar:?]
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96) [javafx.graphics.jar:?]
2021-01-25 11:53:49,594 WARN  [JavaFX Application Thread] (PDQController.java:1648) - IO exception caught file loading file '/Users/Brandon/IdeaProjects/oxfordUniversity/pdq/./.pdq/plans/5_0_1.p'. Cannot invoke "uk.ac.ox.cs.pdq.algebra.RelationalTerm.getInputAttributes()" because "child" is null
```

by further investigations I have discovered that the java method 
**assertSelectionCondition**(SimpleCondition selectionCondition, Attribute[] outputAttributes) in java class **uk.ac.ox.cs.pdq.algebra.SelectionTerm**

is returning false on 
			((ConstantEqualityCondition) selectionCondition).getConstant().getType(); --> java.land.string
			outputAttributes[position].getType(); -->java.lang.Integer

**Comment by BrandonBoyWonder** [comment]
As discussed with @michaelbenedikt this problem could be cause the the sql parser not assigning the correct type from the query. 

Will be looking at setting up a parser to pick up the integer when no quotes is assigned to the value.
